# .github/workflows/sql-deploy.yml
on: [push]

jobs:
  
  deploy:
    runs-on: windows-latest
    steps:
    - name: 'Checking out repo code'
      uses: actions/checkout@v2
    - uses: actions/checkout@v1
#    - uses: azure/login@v1
#      with:
#        creds: ${{ secrets.AZURE_CREDENTIALS }}
 
    - uses: azure/sql-action@v1
      with:
        server-name: xaxle.database.windows.net
        connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
        sql-file: ./testsql.sql
